"""Configuration for the UIUC scout pipeline."""

from __future__ import annotations

UIUC_TRACKS: tuple[str, ...] = (
    "ml_ai_research",
    "uiuc_technical_swe",
    "quant_fintech",
)

UIUC_PING_SCORE_THRESHOLD = 95
UIUC_MAX_PINGS_PER_RUN = 3

ML_AI_KEYWORDS: tuple[str, ...] = (
    "machine learning",
    "ml",
    "artificial intelligence",
    "ai",
    "llm",
    "language model",
    "nlp",
    "knowledge graph",
    "computer vision",
    "vision",
    "deep learning",
    "trustworthy ai",
    "robustness",
    "privacy",
    "research engineer",
    "ml systems",
    "inference",
    "retrieval",
    "ranking",
    "search",
    "scientific computing",
    "health-tech",
    "medical ai",
    "signals",
    "eeg",
)

TECHNICAL_SWE_KEYWORDS: tuple[str, ...] = (
    "software",
    "developer",
    "engineering",
    "systems",
    "platform",
    "backend",
    "python",
    "data",
    "compiler",
    "infra",
    "infrastructure",
    "observability",
    "tooling",
    "distributed systems",
)

QUANT_KEYWORDS: tuple[str, ...] = (
    "quant",
    "quantitative",
    "fintech",
    "trading",
    "systematic trading",
    "risk",
    "forecasting",
    "time series",
    "alpha",
    "market",
    "portfolio",
    "optimization",
    "numerical methods",
)

DEPRIORITIZE_KEYWORDS: tuple[str, ...] = (
    "front desk",
    "office assistant",
    "student assistant",
    "marketing",
    "communications",
    "event staff",
    "administrative",
    "help desk",
    "qa tester",
    "it support",
    "operations",
    "game design",
    "mobile app",
)

STUDENT_SIGNAL_KEYWORDS: tuple[str, ...] = (
    "student",
    "undergraduate",
    "intern",
    "internship",
    "research assistant",
    "assistantship",
    "fellowship",
    "apply",
    "opportunity",
    "program",
    "join",
    "contact",
    "summer",
)

UIUC_COMPANY_ARCHETYPES: dict[str, tuple[str, ...]] = {
    "trustworthy ai": ("Anthropic", "OpenAI"),
    "nlp": ("OpenAI", "Cohere", "Mistral AI"),
    "knowledge graph": ("Google / DeepMind", "Perplexity AI"),
    "computer vision": ("Waymo", "Nvidia", "Snap", "Adobe"),
    "compiler": ("Nvidia", "Databricks"),
    "systems": ("Databricks", "Datadog", "Snowflake"),
    "platform": ("Databricks", "Pinecone", "Datadog"),
    "trading": ("Jane Street", "Hudson River Trading (HRT)", "Jump Trading"),
    "quant": ("Jane Street", "Two Sigma", "Citadel / Citadel Securities"),
    "time series": ("Two Sigma", "Point72 / Cubist", "DRW"),
    "optimization": ("DE Shaw", "Optiver", "IMC Financial Markets"),
    "health-tech": ("Intuit", "Microsoft / Azure AI"),
}

VAULT_PROFILE_SIGNALS: dict[str, tuple[str, ...]] = {
    "ml_ai_research": (
        "AI research experience on RAG, evaluation, and model training work.",
        "Computer vision background from your hackathon win and emotion detector project.",
        "Strong fit for ML/AI engineer and research engineer paths from your Vault.",
    ),
    "uiuc_technical_swe": (
        "Python backend and data-tooling work lines up with technical SWE roles.",
        "Your Flask/SQLite/SQLAlchemy experience supports research tooling and platform work.",
        "SWE roles are favored when they compound into ML/AI or quant directions.",
    ),
    "quant_fintech": (
        "Your backtesting platform and 16 metrics framework support quant-dev and fintech work.",
        "Stats + CS is a strong fit for quantitative research and modeling-heavy paths.",
        "Time-series, optimization, and trading-systems work directly supports the quant lane.",
    ),
}

UIUC_SOURCE_PAGES: tuple[dict[str, object], ...] = (
    {
        "source": "bioe_faculty",
        "url": "https://bioengineering.illinois.edu/people/faculty",
        "parser": "faculty_link_hub",
        "entity_kind": "faculty_profile",
        "unit": "UIUC",
        "department": "Bioengineering",
        "max_profiles": 25,
        "profile_link_pattern": "/people/",
    },
    {
        "source": "ece_ai_faculty",
        "url": "https://ece.illinois.edu/research/crosscutting-themes/ai",
        "parser": "faculty_link_hub",
        "entity_kind": "faculty_profile",
        "unit": "UIUC",
        "department": "ECE",
        "max_profiles": 40,
        "profile_link_pattern": "/about/directory/faculty/",
    },
    {
        "source": "ise_faculty",
        "url": "https://ise.illinois.edu/directory/faculty",
        "parser": "faculty_link_hub",
        "entity_kind": "faculty_profile",
        "unit": "UIUC",
        "department": "ISE",
        "max_profiles": 20,
        "profile_link_pattern": "/directory/profile/",
    },
    {
        "source": "ischool_faculty",
        "url": "https://ischool.illinois.edu/people/faculty",
        "parser": "faculty_link_hub",
        "entity_kind": "faculty_profile",
        "unit": "UIUC",
        "department": "iSchool",
        "max_profiles": 10,
        "profile_link_pattern": "/people/",
    },
    {
        "source": "statistics_faculty",
        "url": "https://stat.illinois.edu/directory",
        "parser": "faculty_link_hub",
        "entity_kind": "faculty_profile",
        "unit": "UIUC",
        "department": "Statistics",
        "max_profiles": 15,
        "profile_link_pattern": "/directory/profile/",
        "use_curl_only": True,
    },
    {
        "source": "neuroscience_faculty",
        "url": "https://neuroscience.illinois.edu/directory/faculty",
        "parser": "faculty_link_hub",
        "entity_kind": "faculty_profile",
        "unit": "UIUC",
        "department": "Neuroscience",
        "max_profiles": 15,
        "profile_link_pattern": "/directory/profile/",
        "use_curl_only": True,
    },
    {
        "source": "uiuc_nlp_faculty",
        "url": "https://nlp.cs.illinois.edu/",
        "parser": "faculty_link_hub",
        "entity_kind": "faculty_profile",
        "unit": "UIUC",
        "department": "CS",
        "max_profiles": 20,
        "profile_link_pattern": "/about/people/faculty/",
    },
    {
        "source": "digital_ag_reu",
        "url": "https://digitalag.illinois.edu/education/reu-program/",
        "parser": "self_page",
        "entity_kind": "research_program",
        "unit": "Center for Digital Agriculture",
        "department": "Digital Agriculture",
    },
    {
        "source": "aifarms",
        "url": "https://aifarms.illinois.edu/",
        "parser": "self_page",
        "entity_kind": "research_group",
        "unit": "AIFARMS Institute",
        "department": "Digital Agriculture",
    },
    {
        "source": "gies_dsrs",
        "url": "https://giesbusiness.illinois.edu/dsrs",
        "parser": "self_page",
        "entity_kind": "research_program",
        "unit": "Gies",
        "department": "Data Science Research Service",
    },
    {
        "source": "gies_gbrl",
        "url": "https://gbrl.giesbusiness.illinois.edu/work-with-gbrl",
        "parser": "self_page",
        "entity_kind": "research_program",
        "unit": "Gies",
        "department": "Gies Business Research Lab",
    },
    {
        "source": "gies_disruption_lab",
        "url": "https://giesbusiness.illinois.edu/disruption-lab",
        "parser": "self_page",
        "entity_kind": "research_group",
        "unit": "Gies",
        "department": "Disruption Lab",
    },
    {
        "source": "ai_in_medicine",
        "url": "https://medicine.illinois.edu/about/aiinmedicine",
        "parser": "self_page",
        "entity_kind": "research_program",
        "unit": "Carle Illinois",
        "department": "AI in Medicine",
    },
    {
        "source": "research_park_sitemap",
        "url": "https://researchpark.illinois.edu/post-sitemap.xml",
        "parser": "research_park_sitemap",
        "entity_kind": "job_posting",
        "unit": "Research Park",
        "department": "Research Park",
        "use_curl_only": True,
    },
    {
        "source": "ncsa_students",
        "url": "https://ncsa.illinois.edu/about/for-students/",
        "parser": "generic",
        "entity_kind": "research_program",
        "unit": "NCSA",
        "department": "NCSA",
    },
    {
        "source": "ncsa_spin",
        "url": "https://spin.ncsa.illinois.edu/",
        "parser": "generic",
        "entity_kind": "research_program",
        "unit": "NCSA",
        "department": "SPIN",
    },
    {
        "source": "undergrad_research",
        "url": "https://careercenter.illinois.edu/undergraduateresearch",
        "parser": "generic",
        "entity_kind": "research_program",
        "unit": "Office of Undergraduate Research",
        "department": "Illinois",
    },
    {
        "source": "ncsa_reu",
        "url": "https://reu.ncsa.illinois.edu/",
        "parser": "generic",
        "entity_kind": "research_program",
        "unit": "NCSA",
        "department": "Research Experiences for Undergraduates",
    },
)

UIUC_SEED_TARGETS: tuple[dict[str, object], ...] = (
    {
        "source": "uiuc_seed",
        "url": "https://grainger.illinois.edu/about/directory/faculty/lbo",
        "entity_kind": "faculty_profile",
        "title": "Bo Li - Trustworthy AI",
        "unit": "UIUC",
        "department": "CS",
        "faculty": "Bo Li",
        "description": "Trustworthy AI, robustness, privacy, and machine learning security research.",
        "contact": "",
        "last_seen": "2026-04-15",
        "status_hint": "unknown",
        "domain_tags": ["trustworthy ai", "privacy", "robustness", "machine learning"],
    },
    {
        "source": "uiuc_seed",
        "url": "https://grainger.illinois.edu/about/directory/faculty/hengji",
        "entity_kind": "faculty_profile",
        "title": "Heng Ji - NLP and Knowledge Graphs",
        "unit": "UIUC",
        "department": "CS",
        "faculty": "Heng Ji",
        "description": "NLP, information extraction, knowledge graphs, and language technologies.",
        "contact": "",
        "last_seen": "2026-04-15",
        "status_hint": "unknown",
        "domain_tags": ["nlp", "knowledge graph", "information extraction", "llm"],
    },
    {
        "source": "uiuc_seed",
        "url": "https://ischool.illinois.edu/research/areas/artificial-intelligence-and-machine-learning",
        "entity_kind": "research_group",
        "title": "iSchool AI and Machine Learning",
        "unit": "UIUC",
        "department": "iSchool",
        "faculty": "",
        "description": "Applied AI, ML, data, and information systems research within Illinois.",
        "contact": "",
        "last_seen": "2026-04-15",
        "status_hint": "rolling",
        "domain_tags": ["machine learning", "data systems", "search"],
    },
    {
        "source": "uiuc_seed",
        "url": "https://experts.illinois.edu/en/persons/victor-duarte/",
        "entity_kind": "faculty_profile",
        "title": "Victor Duarte - Quantitative Finance and Machine Learning",
        "unit": "UIUC",
        "department": "Gies",
        "faculty": "Victor Duarte",
        "description": "Quantitative finance, economics, machine learning, time series, and optimization-oriented research.",
        "contact": "",
        "last_seen": "2026-04-15",
        "status_hint": "rolling",
        "domain_tags": ["quant", "time series", "optimization", "trading"],
    },
    {
        "source": "uiuc_seed",
        "url": "https://ece.illinois.edu/about/directory/faculty/aschwing",
        "entity_kind": "faculty_profile",
        "title": "Alexander Schwing - Generative Models and Computer Vision",
        "unit": "UIUC",
        "department": "ECE",
        "faculty": "Alexander Schwing",
        "description": "Computer vision, machine learning, generative models, and multimodal AI research.",
        "contact": "",
        "last_seen": "2026-04-16",
        "status_hint": "rolling",
        "domain_tags": ["computer vision", "machine learning", "deep learning", "multimodal"],
    },
    {
        "source": "uiuc_seed",
        "url": "https://ece.illinois.edu/about/directory/faculty/huanz",
        "entity_kind": "faculty_profile",
        "title": "Huan Zhang - Trustworthy and Robust AI",
        "unit": "UIUC",
        "department": "ECE",
        "faculty": "Huan Zhang",
        "description": "Trustworthy AI, robustness, verification, and machine learning systems research.",
        "contact": "",
        "last_seen": "2026-04-16",
        "status_hint": "rolling",
        "domain_tags": ["trustworthy ai", "robustness", "verification", "machine learning"],
    },
    {
        "source": "uiuc_seed",
        "url": "https://grainger.illinois.edu/about/directory/faculty/yxw",
        "entity_kind": "faculty_profile",
        "title": "Yuxiong Wang - Computer Vision and Embodied AI",
        "unit": "UIUC",
        "department": "CS",
        "faculty": "Yuxiong Wang",
        "description": "Computer vision, embodied AI, robotics, and perception systems research.",
        "contact": "",
        "last_seen": "2026-04-16",
        "status_hint": "rolling",
        "domain_tags": ["computer vision", "robotics", "perception", "machine learning"],
    },
    {
        "source": "uiuc_seed",
        "url": "https://ece.illinois.edu/about/directory/faculty/zhizhenz",
        "entity_kind": "faculty_profile",
        "title": "Zhizhen Jane Zhao - Computational Imaging and Medical AI",
        "unit": "UIUC",
        "department": "ECE",
        "faculty": "Zhizhen Zhao",
        "description": "Computational imaging, data-driven inverse problems, and medical AI-adjacent research.",
        "contact": "",
        "last_seen": "2026-04-16",
        "status_hint": "rolling",
        "domain_tags": ["medical ai", "signals", "imaging", "machine learning"],
    },
    {
        "source": "uiuc_seed",
        "url": "https://medicine.illinois.edu/about/directory/faculty/profile/jirudaya",
        "entity_kind": "faculty_profile",
        "title": "Joseph Irudayaraj - AI and Biomedical Sensing",
        "unit": "UIUC",
        "department": "Carle Illinois",
        "faculty": "Joseph Irudayaraj",
        "description": "Biomedical sensing, machine learning, and computational medicine research.",
        "contact": "",
        "last_seen": "2026-04-16",
        "status_hint": "rolling",
        "domain_tags": ["medical ai", "health-tech", "machine learning", "signals"],
    },
    {
        "source": "uiuc_seed",
        "url": "https://ece.illinois.edu/about/directory/faculty/krdc",
        "entity_kind": "faculty_profile",
        "title": "Katherine Driggs-Campbell - Safe Autonomy and Robotics",
        "unit": "UIUC",
        "department": "ECE",
        "faculty": "Katherine Driggs-Campbell",
        "description": "Safe autonomy, robotics, perception, and machine learning for real-world systems.",
        "contact": "",
        "last_seen": "2026-04-16",
        "status_hint": "rolling",
        "domain_tags": ["robotics", "perception", "computer vision", "machine learning"],
    },
    {
        "source": "uiuc_seed",
        "url": "https://spin.ncsa.illinois.edu/",
        "entity_kind": "research_program",
        "title": "NCSA SPIN",
        "unit": "NCSA",
        "department": "SPIN",
        "faculty": "",
        "description": "NCSA student-focused pathway for technical internships, applied data work, and research experience.",
        "contact": "",
        "last_seen": "2026-04-16",
        "status_hint": "rolling",
        "domain_tags": ["data", "research engineer", "scientific computing"],
    },
    {
        "source": "uiuc_seed",
        "url": "https://reu.ncsa.illinois.edu/",
        "entity_kind": "research_program",
        "title": "NCSA REU",
        "unit": "NCSA",
        "department": "NCSA",
        "faculty": "",
        "description": "Research Experiences for Undergraduates at NCSA with scientific computing, data, and AI-adjacent research exposure.",
        "contact": "",
        "last_seen": "2026-04-16",
        "status_hint": "open",
        "domain_tags": ["scientific computing", "data", "machine learning"],
    },
)
